### PR TITLE
Rebecca/student route

### LINKED ISSUE #20: As an Admin, I would like to C.R.U.D Students so that I am able to keep the students that are in a course updated and the database up to date.
As an Admin, I would like to C.R.U.D students so that I am able to keep the students that are in a course updated and the database up to date.

### **Acceptance criteria**:
- [x] Create students route
- [x] Read students route
- [x] Update students route
- [x] Delete students route

### PR DESCRIPTION
**Pull request by rebeccarothschild**
Completed implementation of CRUD routes for students.

Things to note:
- You must create a course before you create students. A student must be created for a specific class
- A student will be created and added to all existing instances of a course. For example, if an instructor is adding a student to a course then all students who are already "enrolled" in that course and have it listed in their courses will be updated with the new student.
- In the same way, when an instructor deletes a student from a course, all instances of that course have that student removed from it.
- All instances of a course are updated when a student enrolled in that course is updated.

Closes #20

### CODE REVIEW

**Comment by marcoarceo** [comment]
@rebeccachild74 it looks good to me except that the course.js is missing the courseID when creating which was something that you had requested before. If nothing was changed in the course.js file on your end I would recommend removing that file from the pull request or let me know what you changed so I can implement it in my request and you can remove the file here.

**Comment by rebeccarothschild** [comment]
@marcoarceo Oh good call, I pulled your branch into mine when I started working in it.

**Review by marcoarceo — APPROVED** [review]
The pull request looks great and the code looks well written. Thank you for making the change that I requested previously.

**Review by HatchedCode — APPROVED** [review]
Looks good!

**Pull request merged**
