### PR TITLE
Marco/database

### LINKED ISSUE #9: As an admin, I would like to store all the user's information into a remote database such as mongoDB so that the information can be stored securely and efficiently
- [x] Store user ID
- [x] Store user name
- [x] Store user password
- [x] Store user security question
- [x] Store user security answer
- [x] Store user class list
- [x] Store user questions/answers (questions have a unique id?)(Possibly store Q & A separately)

### PR DESCRIPTION
**Pull request by marcoarceo**
Modified the database schemas inside the server.js file to include all the types of data we will be collecting

### CODE REVIEW

**Review by HatchedCode — APPROVED** [review]
Make sure that the testcafe-workflow.yml file is consistent with that is already in master, but other than that everything else looks good.

**Comment by marcoarceo** [comment]
Okay I will make sure to take that into account in the future

**Comment by rebeccachild74** [comment]
The new schema looks good

**Review by rebeccarothschild — APPROVED** [review]
Looks good

**Review by rebeccarothschild — APPROVED** [review]
Looks good, thanks for making those changes!

**Pull request merged**
