### PR TITLE
Rebecca/manage courses - implemented basic tables for courses & students and allow instructors to upload a csv file of students

### LINKED ISSUE #10: As an instructor, I want to upload my class roster so that I can give polls to a specific class.
- [x] Upload roster as .csv file
- [x] See table of uploaded students

### PR DESCRIPTION
**Pull request by rebeccarothschild**
### Overview
This PR builds out the basic UI for the courses mode of the application. It provides different UI views and capabilities to different user types. A student can see a table of the courses they are in and a table of the students in each course. An instructor can see the same, but they also have the option of adding/deleting a course & adding/deleting/uploading a roster of students.

### Details
In this PR, only the upload students functionality has been implemented. The rest of the CRUD requests mentioned in the overview have been stubbed. When an instructor uploads a class roster, the file must be of type .csv. Each row in the .csv file should have the below schema, I've added an [example file](https://emailwsu.sharepoint.com/:x:/r/teams/2020.fall.PULLM.Cpt.S.489-2.Kliks/Shared%20Documents/2.%20Kliks/example_roster.csv?d=w15ed0f4e160d4af3a1a2adc5cb5e72fd&csf=1&web=1&e=1inpRZ) to our teams page.

image
 
A roster can have the title row, but it does not have to.

### Testing
Testing these changes and the rest of Courses implementation will be completed in Issue #30 

Closes #10

### CODE REVIEW

**Review by HatchedCode — CHANGES_REQUESTED** [review]
There were a few things that I noticed:
-I am unsure how to add students to a course. 
-I have tried to find the sidemenu options for courses mode but it seems like they are not being loaded.


Side notes/questions:
-Is there a way to add courses?


Can you look in these things? Thanks!

**Comment by rebeccarothschild** [comment]
@HatchedCode As noted in the PR description, I have only implemented the upload students functionality to address Issue #10. The ability to add, delete, and update a course in the UI & individually add, delete, and update a student in the UI has been not been implemented yet. For this PR I've only implemented what was necessary for Issue #10. I will create a follow up issue to complete the courses mode implementation including updating the sidemenu.

To view my changes in the app, you can login using the instructor@wsu.edu and rebecca@wsu.edu accounts.

Edit: Created Issue #32 to complete the courses mode implementation. Feel free to add to it

**Comment by HatchedCode** [comment]
> @HatchedCode As noted in the PR description, I have only implemented the upload students functionality to address Issue #10. The ability to add, delete, and update a course in the UI & individually add, delete, and update a student in the UI has been not been implemented yet. For this PR I've only implemented what was necessary for Issue #10. I will create a follow up issue to complete the courses mode implementation including updating the sidemenu.
> 
> To view my changes in the app, you can login using the [instructor@wsu.edu](mailto:instructor@wsu.edu) and [rebecca@wsu.edu](mailto:rebecca@wsu.edu) accounts.
> 
> Edit: Created Issue #32 to complete the courses mode implementation. Feel free to add to it

**Makes sense and please create that issue so that we have the ability to do that. If that is the case, then this PR is ready to get checked into master.**


**Good work!**

**Review by HatchedCode — APPROVED** [review]
Good to go. Meets the requirements of the linked issue.

**Pull request merged**
